spring:
  datasource:
    url: jdbc:mysql://localhost:3306/signaldb
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  mybatis-plus:
#    mapper-locations: classpath:/mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
  logging:
    config: classpath:logback-spring.xml
